name: xyz
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

fonts:
  - family: Sunflower
    fonts:
      - asset: assets/font/Sunflower/SunFlower-Bold.ttf
        weight: 700
      - asset: assets/font/Sunflower/SunFlower-Light.ttf
        weight: 200
      - asset: assets/font/Sunflower/SunFlower-Medium.ttf
        weight: 500
      